name: "Doc: sphinx to gh-pages"
on:
  push:
    branches:
    - He

jobs:
  sphinx_2_gp_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
        # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: "3.10"
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: build doc
      run: |
        sphinx-apidoc -o docs/ . -f
        cd docs && make html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html/
