name: "Unit test"
on:
  push:
    branches:
    - master
    - He 
    - dev

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
        # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install .
        pip install .[test]
    - name: type test
      run: |
        mypy --ignore-missing-imports oi_cli2/cli/main.py 
    - name: unit test
      run: |
        pytest tests
